spring:
  datasource:
    username: root
    password: 1234567abcd~@A
    url: jdbc:mysql://47.104.191.228:3306/boringfish?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8087
  servlet:
    session:
      timeout: PT2H #2H